### ISSUE TITLE
AS A USER i want a fun / random todo, check it and save it in a private list

### ISSUE THREAD

**Issue by bumsausende** [bumsausende/capstone-doh#7]
- [ ] create buttons to decide between inside or outside
- [ ] create a local db ( with JSONs) , just to start with (later mongoDB)
- [ ] add random todo function ( math random / algorythm?) as main function , then for each inside and outside toDOHs, import local JSON, open with modal or single page?
- [ ] do the ToDOH via timestamp? one per day?
- [ ] create a WELL DONE / HERO page, if toDOHs is checked/done
- [ ] save it in a personal List (order?) - create a profile

criteria of acceptance

- [ ] random toDOH is lots of fun and saved in personal profile
